name: cloudflare pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [content_update, blog_update]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/jdx/mise:2026.9.6
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: Install dependencies & deploy
        run: |
            mise deps
            mise run fetch
            mise run build
            # mise run deploy
            # mise run deploy1

        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}



      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
